/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package real.estate;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author RISHI DESAI
 */
public class Flats3 extends javax.swing.JFrame {
    String tower = "tower 3";
    /**
     * Creates new form Flats3
     */
    public Flats3() {
        initComponents();
        String query = "SELECT * FROM `tower 3`";
        PreparedStatement ps;
        ResultSet rs;
        try{
        ps = MyConnection.getConnection().prepareStatement(query);
        rs=ps.executeQuery();
        while(rs.next()){
            switch(rs.getString("flatsSold")){
                case "101":
                    flat101.setEnabled(false);
                    break;
                case "102":
                    flat102.setEnabled(false);
                    break;
                case "103":
                    flat103.setEnabled(false);
                    break;
                case "201":
                    flat201.setEnabled(false);
                    break;
                case "202":
                    flat202.setEnabled(false);
                    break;
                case "203":
                    flat203.setEnabled(false);
                    break;
                case "301":
                    flat301.setEnabled(false);
                    break;
                case "302":
                    flat302.setEnabled(false);
                    break;
                case "303":
                    flat303.setEnabled(false);
                    break;
                case "401":
                    flat401.setEnabled(false);
                    break;
                case "402":
                    flat402.setEnabled(false);
                    break;
                case "403":
                    flat403.setEnabled(false);
                    break;
                case "501":
                    flat501.setEnabled(false);
                    break;
                case "502":
                    flat502.setEnabled(false);
                    break;
                case "503":
                    flat503.setEnabled(false);
                    break;
                case "601":
                    flat601.setEnabled(false);
                    break;
                case "602":
                    flat602.setEnabled(false);
                    break;
                case "603":
                    flat603.setEnabled(false);
                    break;
            }
        }
        }
        catch(SQLException ex){
            Logger.getLogger(Flats3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        flat101 = new javax.swing.JButton();
        flat102 = new javax.swing.JButton();
        flat103 = new javax.swing.JButton();
        flat201 = new javax.swing.JButton();
        flat202 = new javax.swing.JButton();
        flat203 = new javax.swing.JButton();
        flat303 = new javax.swing.JButton();
        flat302 = new javax.swing.JButton();
        flat301 = new javax.swing.JButton();
        flat403 = new javax.swing.JButton();
        flat402 = new javax.swing.JButton();
        flat401 = new javax.swing.JButton();
        flat503 = new javax.swing.JButton();
        flat502 = new javax.swing.JButton();
        flat501 = new javax.swing.JButton();
        flat603 = new javax.swing.JButton();
        flat602 = new javax.swing.JButton();
        flat601 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("TOWER 3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        flat101.setText("101");
        flat101.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                flat101FocusLost(evt);
            }
        });
        flat101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat101ActionPerformed(evt);
            }
        });

        flat102.setText("102");
        flat102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat102ActionPerformed(evt);
            }
        });

        flat103.setText("103");
        flat103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat103ActionPerformed(evt);
            }
        });

        flat201.setText("201");
        flat201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat201ActionPerformed(evt);
            }
        });

        flat202.setText("202");
        flat202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat202ActionPerformed(evt);
            }
        });

        flat203.setText("203");
        flat203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat203ActionPerformed(evt);
            }
        });

        flat303.setText("303");
        flat303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat303ActionPerformed(evt);
            }
        });

        flat302.setText("302");
        flat302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat302ActionPerformed(evt);
            }
        });

        flat301.setText("301");
        flat301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat301ActionPerformed(evt);
            }
        });

        flat403.setText("403");
        flat403.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat403ActionPerformed(evt);
            }
        });

        flat402.setText("402");
        flat402.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat402ActionPerformed(evt);
            }
        });

        flat401.setText("401");
        flat401.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat401ActionPerformed(evt);
            }
        });

        flat503.setText("503");
        flat503.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat503ActionPerformed(evt);
            }
        });

        flat502.setText("502");
        flat502.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat502ActionPerformed(evt);
            }
        });

        flat501.setText("501");
        flat501.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat501ActionPerformed(evt);
            }
        });

        flat603.setText("603");
        flat603.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat603ActionPerformed(evt);
            }
        });

        flat602.setText("602");
        flat602.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat602ActionPerformed(evt);
            }
        });

        flat601.setText("601");
        flat601.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flat601ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(flat301, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(flat401, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flat501, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flat601, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flat201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flat101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(flat302, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(flat502, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(flat402, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(flat202, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(flat102, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(flat602, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(flat603, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(flat503, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(flat103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(flat403, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(flat303, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(flat203, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flat603)
                    .addComponent(flat602)
                    .addComponent(flat601))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flat503)
                    .addComponent(flat502)
                    .addComponent(flat501))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flat403)
                    .addComponent(flat402)
                    .addComponent(flat401))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flat303)
                    .addComponent(flat302)
                    .addComponent(flat301))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flat201)
                    .addComponent(flat202)
                    .addComponent(flat203))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flat101)
                    .addComponent(flat102)
                    .addComponent(flat103))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flat101FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_flat101FocusLost

    }//GEN-LAST:event_flat101FocusLost

    private void flat101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat101ActionPerformed
        String flat="101";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat101ActionPerformed

    private void flat102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat102ActionPerformed
        String flat="102";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat102ActionPerformed

    private void flat103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat103ActionPerformed
        String flat="103";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat103ActionPerformed

    private void flat201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat201ActionPerformed
        String flat="201";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat201ActionPerformed

    private void flat202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat202ActionPerformed
        String flat="202";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat202ActionPerformed

    private void flat203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat203ActionPerformed
        String flat="203";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat203ActionPerformed

    private void flat303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat303ActionPerformed
        String flat="303";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat303ActionPerformed

    private void flat302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat302ActionPerformed
        String flat="302";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat302ActionPerformed

    private void flat301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat301ActionPerformed
        String flat="301";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat301ActionPerformed

    private void flat403ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat403ActionPerformed
        String flat="403";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat403ActionPerformed

    private void flat402ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat402ActionPerformed
        String flat="402";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat402ActionPerformed

    private void flat401ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat401ActionPerformed
        String flat="401";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat401ActionPerformed

    private void flat503ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat503ActionPerformed
        String flat="503";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat503ActionPerformed

    private void flat502ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat502ActionPerformed
        String flat="502";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat502ActionPerformed

    private void flat501ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat501ActionPerformed
        String flat="501";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat501ActionPerformed

    private void flat603ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat603ActionPerformed
        String flat="603";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat603ActionPerformed

    private void flat602ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat602ActionPerformed
        String flat="602";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat602ActionPerformed

    private void flat601ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flat601ActionPerformed
        String flat="601";
        new SELLER_PORTAL(flat,tower).setVisible(true);
    }//GEN-LAST:event_flat601ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flats3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flats3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flats3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flats3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flats3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton flat101;
    private javax.swing.JButton flat102;
    private javax.swing.JButton flat103;
    private javax.swing.JButton flat201;
    private javax.swing.JButton flat202;
    private javax.swing.JButton flat203;
    private javax.swing.JButton flat301;
    private javax.swing.JButton flat302;
    private javax.swing.JButton flat303;
    private javax.swing.JButton flat401;
    private javax.swing.JButton flat402;
    private javax.swing.JButton flat403;
    private javax.swing.JButton flat501;
    private javax.swing.JButton flat502;
    private javax.swing.JButton flat503;
    private javax.swing.JButton flat601;
    private javax.swing.JButton flat602;
    private javax.swing.JButton flat603;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
